apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-platform.fullname" . }}
  labels:
    {{- include "hello-platform.labels" . | nindent 4 }}
data:
  APPLICATION_NAME: {{ .Values.env.APPLICATION_NAME | quote }}
  ENVIRONMENT: {{ .Values.env.ENVIRONMENT | quote }}
  VERSION: {{ .Values.env.VERSION | quote }}
